const constants = {
  FETCH_ARTICLES: "FETCH_ARTICLES",
  SET_ARTICLE_TO_DISPLAY: "SET_ARTICLE_TO_DISPLAY",
  SET_VISITED_ARTICLE: "SET_VISITED_ARTICLE",
  SET_SEEN_ENGAGDET_ARTICLE: "SET_SEEN_ENGAGDET_ARTICLE"
}

export default constants;